// <auto-generated />
using CoffeeShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Freeze"
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "product.view",
                            Module = "Product",
                            Name = "Xem sản phẩm"
                        },
                        new
                        {
                            Id = 2,
                            Code = "product.create",
                            Module = "Product",
                            Name = "Tạo sản phẩm"
                        },
                        new
                        {
                            Id = 3,
                            Code = "product.update",
                            Module = "Product",
                            Name = "Sửa sản phẩm"
                        },
                        new
                        {
                            Id = 4,
                            Code = "product.delete",
                            Module = "Product",
                            Name = "Xóa sản phẩm"
                        },
                        new
                        {
                            Id = 5,
                            Code = "category.view",
                            Module = "Category",
                            Name = "Xem danh mục"
                        },
                        new
                        {
                            Id = 6,
                            Code = "category.create",
                            Module = "Category",
                            Name = "Tạo danh mục"
                        },
                        new
                        {
                            Id = 7,
                            Code = "category.update",
                            Module = "Category",
                            Name = "Sửa danh mục"
                        },
                        new
                        {
                            Id = 8,
                            Code = "category.delete",
                            Module = "Category",
                            Name = "Xóa danh mục"
                        },
                        new
                        {
                            Id = 9,
                            Code = "order.view.own",
                            Module = "Order",
                            Name = "Xem đơn hàng của mình"
                        },
                        new
                        {
                            Id = 10,
                            Code = "order.view.all",
                            Module = "Order",
                            Name = "Xem tất cả đơn hàng"
                        },
                        new
                        {
                            Id = 11,
                            Code = "order.create",
                            Module = "Order",
                            Name = "Tạo đơn hàng"
                        },
                        new
                        {
                            Id = 12,
                            Code = "order.update.own",
                            Module = "Order",
                            Name = "Sửa đơn hàng của mình"
                        },
                        new
                        {
                            Id = 13,
                            Code = "order.update.all",
                            Module = "Order",
                            Name = "Sửa tất cả đơn hàng"
                        },
                        new
                        {
                            Id = 14,
                            Code = "order.cancel.own",
                            Module = "Order",
                            Name = "Hủy đơn của mình"
                        },
                        new
                        {
                            Id = 15,
                            Code = "order.cancel.all",
                            Module = "Order",
                            Name = "Hủy bất kỳ đơn nào"
                        },
                        new
                        {
                            Id = 16,
                            Code = "user.view.own",
                            Module = "User",
                            Name = "Xem thông tin cá nhân"
                        },
                        new
                        {
                            Id = 17,
                            Code = "user.view.all",
                            Module = "User",
                            Name = "Xem tất cả user"
                        },
                        new
                        {
                            Id = 18,
                            Code = "user.update.own",
                            Module = "User",
                            Name = "Sửa thông tin cá nhân"
                        },
                        new
                        {
                            Id = 19,
                            Code = "user.update.all",
                            Module = "User",
                            Name = "Sửa thông tin user khác"
                        },
                        new
                        {
                            Id = 20,
                            Code = "user.delete",
                            Module = "User",
                            Name = "Xóa user"
                        },
                        new
                        {
                            Id = 21,
                            Code = "role.manage",
                            Module = "System",
                            Name = "Quản lý role"
                        },
                        new
                        {
                            Id = 22,
                            Code = "permission.assign",
                            Module = "System",
                            Name = "Phân quyền"
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Cà phê Robusta đậm đặc hương vị truyền thống",
                            Name = "Cà phê đen đá"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Sữa nóng pha thêm chút cà phê, ngọt ngào",
                            Name = "Bạc xỉu"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Bánh sừng bò ngàn lớp thơm bơ",
                            Name = "Bánh Croissant"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Hương vị cà phê Việt Nam truyền thống kết hợp sữa đặc",
                            Name = "Cà phê sữa đá"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Espresso nhẹ nhàng hòa quyện với lớp sữa tươi đánh nóng",
                            Name = "Latte Nóng"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Sự cân bằng hoàn hảo giữa Espresso, sữa nóng và bọt sữa",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Espresso pha loãng với nước và đá, thanh nhẹ",
                            Name = "Americano Đá"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Sữa tươi, vani, Espresso và sốt Caramel ngọt ngào",
                            Name = "Caramel Macchiato"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Trà đen thơm lừng kết hợp đào ngâm và sả tươi",
                            Name = "Trà Đào Cam Sả"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Trà ô long thanh mát kết hợp hạt sen bùi bùi",
                            Name = "Trà Sen Vàng"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Vị ngọt ngào của vải thiều hòa quyện hương hoa hồng",
                            Name = "Trà Vải Hoa Hồng"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Bột trà xanh Nhật Bản xay nhuyễn với sữa tươi",
                            Name = "Matcha Đá Xay"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Bánh Oreo xay cùng sữa và đá, phủ lớp kem tươi",
                            Name = "Cookie Đá Xay"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Bánh ngọt vị cà phê và rượu rum, lớp kem phô mai",
                            Name = "Tiramisu"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Bánh phô mai chua ngọt vị chanh dây",
                            Name = "Cheesecake Chanh Dây"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Bánh mousse mềm mịn đậm đà vị sô cô la",
                            Name = "Mousse Chocolate"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Bánh mì que giòn rụm với nhân pate cay nồng",
                            Name = "Bánh Mì Que Pate"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Bánh vòng chiên phủ lớp sốt socola đen",
                            Name = "Bánh Donut Socola"
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 20000m,
                            ProductId = 1,
                            Size = "S"
                        },
                        new
                        {
                            Id = 2,
                            Price = 25000m,
                            ProductId = 1,
                            Size = "M"
                        },
                        new
                        {
                            Id = 3,
                            Price = 30000m,
                            ProductId = 1,
                            Size = "L"
                        },
                        new
                        {
                            Id = 4,
                            Price = 28000m,
                            ProductId = 2,
                            Size = "S"
                        },
                        new
                        {
                            Id = 5,
                            Price = 35000m,
                            ProductId = 2,
                            Size = "M"
                        },
                        new
                        {
                            Id = 6,
                            Price = 45000m,
                            ProductId = 3,
                            Size = "M"
                        },
                        new
                        {
                            Id = 7,
                            Price = 35000m,
                            ProductId = 3,
                            Size = "S"
                        },
                        new
                        {
                            Id = 8,
                            Price = 29000m,
                            ProductId = 4,
                            Size = "M"
                        },
                        new
                        {
                            Id = 9,
                            Price = 35000m,
                            ProductId = 4,
                            Size = "L"
                        },
                        new
                        {
                            Id = 10,
                            Price = 45000m,
                            ProductId = 5,
                            Size = "M"
                        },
                        new
                        {
                            Id = 11,
                            Price = 55000m,
                            ProductId = 5,
                            Size = "L"
                        },
                        new
                        {
                            Id = 12,
                            Price = 45000m,
                            ProductId = 6,
                            Size = "M"
                        },
                        new
                        {
                            Id = 13,
                            Price = 55000m,
                            ProductId = 6,
                            Size = "L"
                        },
                        new
                        {
                            Id = 14,
                            Price = 35000m,
                            ProductId = 7,
                            Size = "M"
                        },
                        new
                        {
                            Id = 15,
                            Price = 41000m,
                            ProductId = 7,
                            Size = "L"
                        },
                        new
                        {
                            Id = 16,
                            Price = 50000m,
                            ProductId = 8,
                            Size = "M"
                        },
                        new
                        {
                            Id = 17,
                            Price = 60000m,
                            ProductId = 8,
                            Size = "L"
                        },
                        new
                        {
                            Id = 18,
                            Price = 45000m,
                            ProductId = 9,
                            Size = "M"
                        },
                        new
                        {
                            Id = 19,
                            Price = 55000m,
                            ProductId = 9,
                            Size = "L"
                        },
                        new
                        {
                            Id = 20,
                            Price = 45000m,
                            ProductId = 10,
                            Size = "M"
                        },
                        new
                        {
                            Id = 21,
                            Price = 55000m,
                            ProductId = 10,
                            Size = "L"
                        },
                        new
                        {
                            Id = 22,
                            Price = 42000m,
                            ProductId = 11,
                            Size = "M"
                        },
                        new
                        {
                            Id = 23,
                            Price = 52000m,
                            ProductId = 11,
                            Size = "L"
                        },
                        new
                        {
                            Id = 24,
                            Price = 55000m,
                            ProductId = 12,
                            Size = "M"
                        },
                        new
                        {
                            Id = 25,
                            Price = 65000m,
                            ProductId = 12,
                            Size = "L"
                        },
                        new
                        {
                            Id = 26,
                            Price = 55000m,
                            ProductId = 13,
                            Size = "M"
                        },
                        new
                        {
                            Id = 27,
                            Price = 65000m,
                            ProductId = 13,
                            Size = "L"
                        },
                        new
                        {
                            Id = 28,
                            Price = 39000m,
                            ProductId = 14,
                            Size = "M"
                        },
                        new
                        {
                            Id = 29,
                            Price = 29000m,
                            ProductId = 14,
                            Size = "S"
                        },
                        new
                        {
                            Id = 30,
                            Price = 39000m,
                            ProductId = 15,
                            Size = "M"
                        },
                        new
                        {
                            Id = 31,
                            Price = 29000m,
                            ProductId = 15,
                            Size = "S"
                        },
                        new
                        {
                            Id = 32,
                            Price = 35000m,
                            ProductId = 16,
                            Size = "M"
                        },
                        new
                        {
                            Id = 33,
                            Price = 25000m,
                            ProductId = 16,
                            Size = "S"
                        },
                        new
                        {
                            Id = 34,
                            Price = 15000m,
                            ProductId = 17,
                            Size = "1 cái"
                        },
                        new
                        {
                            Id = 35,
                            Price = 39000m,
                            ProductId = 17,
                            Size = "Combo 3 cái"
                        },
                        new
                        {
                            Id = 36,
                            Price = 25000m,
                            ProductId = 18,
                            Size = "M"
                        },
                        new
                        {
                            Id = 37,
                            Price = 15000m,
                            ProductId = 18,
                            Size = "S"
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CUSTOMER",
                            Name = "Khách hàng"
                        },
                        new
                        {
                            Id = 3,
                            Code = "STAFF",
                            Name = "Nhân viên"
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        });
                });

            modelBuilder.Entity("CoffeeShopApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Product", b =>
                {
                    b.HasOne("CoffeeShopApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.ProductDetail", b =>
                {
                    b.HasOne("CoffeeShopApi.Models.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.RolePermission", b =>
                {
                    b.HasOne("CoffeeShopApi.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopApi.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.User", b =>
                {
                    b.HasOne("CoffeeShopApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("CoffeeShopApi.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
